# Generated by Django 3.2.10 on 2022-01-07 00:17


"""
/!\ IMPORTANT /!\

https://code.djangoproject.com/ticket/23422?cversion=1&cnum_hist=25

"""


from django.db import migrations
from django.contrib.auth.models import Permission, Group
from django.contrib.auth.management import create_permissions

from crm.constants import SELLING_TEAM_NAME, SUPPORT_TEAM_NAME, SELLING_TEAM_PERMISSIONS, SUPPORT_TEAM_PERMISSIONS


def generate_groups(apps, schema_editor):
    def create_permissions_to_avoid_contenttype_error():
        for app_config in apps.get_app_configs():
            app_config.models_module = True
            create_permissions(app_config, verbosity=0)
            app_config.models_module = None

    def generate_a_group_and_its_permissions(name):
        group_name = globals()[name+"_NAME"]
        group_permissions = globals()[name+"_PERMISSIONS"]

        group, created = Group.objects.get_or_create(name=group_name)
        for permission_natural_key in group_permissions:
            permission = Permission.objects.get_by_natural_key(*permission_natural_key)
            group.permissions.add(permission)

    create_permissions_to_avoid_contenttype_error()
    generate_a_group_and_its_permissions("SELLING_TEAM")
    generate_a_group_and_its_permissions("SUPPORT_TEAM")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(generate_groups),
    ]
